name: Unit Tests & Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Rubocop_converter
        run: cd TemperatureConverter && bundle exec rubocop
      - name: Rubocop_Valera
        run: cd Valera && bundle exec rubocop
      - name: RSpec Lab1
        run: cd TemperatureConverter && bundle exec rspec
      - name: RSpec Valera
        run: cd Valera && bundle exec rspec
